#Author: William Kim
#Date: 10/1/2015
#Description: makefile

#target: dependencies
#	rule to build
#

die: Die.cpp Die.hpp LoadedDie.cpp LoadedDie.hpp Main.cpp
	g++ -std=c++0x Die.cpp LoadedDie.cpp Main.cpp -o die

clean: 
	rm -f *.o *a.out
